name: CI

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: demo-511:${{ github.sha }}

jobs:
  image_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Scan image (Trivy)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: image
          image-ref: ${{ env.IMAGE_NAME }}
          format: table
          output: trivy.txt
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL

      - name: Upload Trivy report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trivy-${{ github.run_number }}
          path: trivy.txt
          retention-days: 7
